# Reusable workflow to setup a specific WMCore component for pip

on:
  workflow_call:
    inputs:
      wmcore_component:
        required: true
        type: string

jobs:
  build_and_publish_from_template:
    runs-on: ubuntu-latest
    environment:
      name: production
    permissions:
      id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing
    steps:
      - uses: actions/checkout@v4
      - name: Setup python 3.8
        uses: actions/setup-python@v5
        with:
          python-version: "3.8"
      - name: Upgrade pip3
        run: |
          python3 -m pip install --upgrade pip
      - name: Update the setup script template with package name
        run: |
          sed "s/PACKAGE_TO_BUILD/${{ inputs.wmcore_component }}/" setup_template.py > setup.py
      - name: Create requirements file
        run: |
          cp requirements.txt requirements.wmcore.txt
          awk "/(${{ inputs.wmcore_component }}$)|(${{ inputs.wmcore_component }},)/ {print \$1}" requirements.wmcore.txt > requirements.txt
      - name: Build sdist
        run: python3 setup.py clean sdist
      - name: List contents before attestation
        run: |
          ls ${{ github.workspace }}
          ls ${{ github.workspace }}/dist
      - name: Attest package
        uses: actions/attest-build-provenance@v1
        with:
          subject-path: '${{ github.workspace }}/dist/${{ inputs.wmcore_component }}-*'
      - name: Upload package distribution to PyPi
        uses: pypa/gh-action-pypi-publish@release/v1
